apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-ing.yml

# Setup
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/0namespace-namespace.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0probeCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/setup/prometheus-operator-serviceAccount.yaml

# Alert Manager
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-podDisruptionBudget.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-prometheusRule.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-secret.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-service.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-serviceAccount.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-serviceMonitor.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/alertmanager-alertmanager.yaml

# BlackBox Exporter
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-clusterRole.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-clusterRoleBinding.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-configuration.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-deployment.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-service.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-serviceAccount.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/blackbox-exporter-serviceMonitor.yaml

# Grafana
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-dashboardDatasources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-dashboardDefinitions.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-dashboardSources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/grafana-serviceMonitor.yaml

# Kube-Prometheus Rule
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-prometheus-prometheusRule.yaml

# Kube-State-Metrics
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kube-state-metrics-serviceMonitor.yaml

# Kubernetes
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-serviceMonitorApiserver.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-serviceMonitorCoreDNS.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-serviceMonitorKubeControllerManager.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-serviceMonitorKubeScheduler.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/kubernetes-serviceMonitorKubelet.yaml

# Node Exporter
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-clusterRole.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-clusterRoleBinding.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-daemonset.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-prometheusRule.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-service.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-serviceAccount.yaml
#- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/node-exporter-serviceMonitor.yaml

# Prometheus Adapter
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-apiService.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-clusterRoleBindingDelegator.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-clusterRoleServerResources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-configMap.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-podDisruptionBudget.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-roleBindingAuthReader.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-adapter-serviceMonitor.yaml

# Prometheus
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-operator-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-operator-serviceMonitor.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-podDisruptionBudget.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-prometheus.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-roleBindingConfig.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-roleBindingSpecificNamespaces.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-roleConfig.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-roleSpecificNamespaces.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.9/manifests/prometheus-serviceMonitor.yaml

patches:
- prometheus-adapter-deployment.yml 
- prometheus-prometheus-patch.yml
